### ISSUE TITLE
Timings support

### ISSUE THREAD

**Issue by parlough** [LanternPowered/LanternServer#27]
This is fairly low priority, as it does not have much use for now, but should definitely be taken on eventually. Some plugins depend on it and overall it will be nice for performance profiling. 

I will probably handle this in a while as I have some of the work already done.

**Comment by Cybermaxke** [comment]
"I think that I would prefer timings to be handled by a plugin, rather then in lantern itself. It's one more thing that we don't have to implement ourselves and we don't have to keep up to date.

Especially with the release of spark. I already tested it with lantern and it's working well. But with lantern you will need to time all the threads, because of the multithreaded worlds."

See https://github.com/LanternPowered/LanternServer/pull/28
